model:
  chemical_species: 'auto'
  cutoff: 6.0
  channel: 32
  lmax: 2
  num_convolution_layer: 4

train:
  random_seed: 1
  num_workers: 4
  epoch: 500
  is_train_stress: True
  is_train_bec: True
  is_train_dielectric: True
  loss: 'mse'
  optimizer: 'adam'
  optim_param:
      lr: 0.005
  scheduler: 'exponentiallr'
  scheduler_param:
      gamma: 0.992
  energy_loss_weight: 1.0
  force_loss_weight: 0.1
  bec_loss_weight: 10.0
  dielectric_loss_weight: 1.0
  stress_loss_weight: 1.0e-6
  per_epoch: 100
  error_record:
    - ['Energy', 'RMSE']
    - ['Force', 'RMSE']
    - ['Stress', 'RMSE']
    - ['BornEffectiveCharges', 'DiagRMSE']
    - ['BornEffectiveCharges', 'OffDiagRMSE']
    - ['DielectricTensor', 'RMSE']
    - ['TotalLoss', 'None']

data:
  batch_size: 4
  shift: 'per_atom_energy_mean'
  scale: 1.0
  data_format: 'ase'
  data_format_args:
    format: 'extxyz'
    index: '::'

  load_trainset_path: ['/home1/augustin/Projects/SevenNet_BEC/data/zro2/dielectric/miniset_200_train.xyz']
  load_validset_path: ['/home1/augustin/Projects/SevenNet_BEC/data/zro2/dielectric/miniset_200_val.xyz']
  load_testset_path:  ['/home1/augustin/Projects/SevenNet_BEC/data/zro2/dielectric/miniset_200_test.xyz']
